# Generated by Django 5.1.2 on 2024-10-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massimo_gagliardi_preentrega3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
