# Generated by Django 5.1.2 on 2024-10-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('massimo_gagliardi_preentrega3', '0002_alter_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
