# Generated by Django 5.1.2 on 2024-10-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('massimo_gagliardi_preentrega3', '0003_alter_producto_stock'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='Productos',
        ),
    ]
